project:
  type: book

book:
  title: "demo"
  downloads: ["pdf"]
  author: "Norah Jones"
  date: "8/5/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    logo: JPEG_example_flower.jpg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
